import Head from "next/head";
import { useState } from "react";
import Button from "~/components/Button";
import Checkbox from "~/components/Checkbox";
import Dropdown, { TDropdownValue } from "~/components/Dropdown";
import Layout from "~/components/Layout";
import TextField from "~/components/TextField";
import { api } from "~/utils/api";

const statuses = [{ name: "To do" }, { name: "Doing" }, { name: "Done" }];

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [fieldValue, setFieldValue] = useState("");
  const [checked, setChecked] = useState(false);
  const [dropdownValue, setDropdownValue] = useState<TDropdownValue>();

  return (
    <>
      <Head>
        <title>Kanban Board</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  );
}
