import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Button from "~/components/Button";
import Checkbox from "~/components/Checkbox";
import TextField from "~/components/TextField";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [fieldValue, setFieldValue] = useState("");
  const [checked, setChecked] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-h-xl">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <Button variant="secondary" size="large">
            Button Primary (L)
          </Button>
          <div className="w-[300px]">
            <TextField
              id="id"
              label="Text Field (Idle)"
              value={fieldValue}
              onChange={(v) => {
                setFieldValue(v.target.value);
              }}
              placeholder="Enter task name"
              errorMessage="Can't be empty"
            />
          </div>
          <div className="w-[300px]">
            <Checkbox
              id="id-chk"
              label="Text Field (Idle)"
              checked={checked}
              onChange={(v) => {
                setChecked(v.target.checked);
              }}
            />
          </div>
          <p className="text-2xl">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
